### ISSUE TITLE
cordova not available!

### ISSUE THREAD

**Issue by psks1204** [rajayogan/ionic2-musicapp#1]
I have the latest version of Ionic CLi and cordova installed. I can't figure out why I'm getting this error while running in Ionic serve. hope you can help.
![capture](https://cloud.githubusercontent.com/assets/22336001/20070864/1962ab94-a548-11e6-9792-7a21cacf3fac.PNG)

**Comment by rajayogan** [comment]
Cordova plugins would be supported only in a mobile device. Kindly use either an android/iOS device or use your emulator to test the code. Thanks.
